<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SYNPSZD4426" name="main.ManualUserStories.US_182094" tests="19" failures="1" timestamp="30 May 2018 15:42:34 GMT" time="822.256" errors="0">
  <testcase name="tc_17" time="49.817" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_06" time="44.684" classname="main.ManualUserStories.US_182094">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at main.ManualUserStories.US_182094.tc_06(US_182094.java:390)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- tc_06 -->
  <testcase name="tc_04" time="31.193" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_15" time="49.149" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_14" time="35.488" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_19" time="51.910" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_07" time="30.877" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_01" time="37.772" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_08" time="46.201" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_11" time="44.328" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_13" time="52.763" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_03" time="42.150" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_02" time="40.222" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_09" time="46.920" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_16" time="47.973" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_05" time="46.466" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_10" time="29.393" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_12" time="49.057" classname="main.ManualUserStories.US_182094"/>
  <testcase name="tc_18" time="45.893" classname="main.ManualUserStories.US_182094"/>
</testsuite> <!-- main.ManualUserStories.US_182094 -->
